services:
  # Application Container (only this one for now)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: skybrokersystem:6.0.0
    container_name: sbs_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=skybrokersystem
      - DB_USERNAME=skybroker
      - DB_PASSWORD=secure_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - skybrokersystem

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: sbs_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: skybrokersystem
      MYSQL_USER: skybroker
      MYSQL_PASSWORD: secure_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skybrokersystem
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: sbs_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skybrokersystem

  # Mailpit (Email Testing)
  mailpit:
    image: axllent/mailpit:latest
    container_name: sbs_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - skybrokersystem

networks:
  skybrokersystem:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
