<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \App\Entity\Customer implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'companyName' => [parent::class, 'companyName', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'customerUsers' => [parent::class, 'customerUsers', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invitations' => [parent::class, 'invitations', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null],
        "\0".parent::class."\0".'regon' => [parent::class, 'regon', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'vatNumber' => [parent::class, 'vatNumber', null],
        'address' => [parent::class, 'address', null],
        'city' => [parent::class, 'city', null],
        'companyName' => [parent::class, 'companyName', null],
        'country' => [parent::class, 'country', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'customerUsers' => [parent::class, 'customerUsers', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'invitations' => [parent::class, 'invitations', null],
        'phone' => [parent::class, 'phone', null],
        'postalCode' => [parent::class, 'postalCode', null],
        'regon' => [parent::class, 'regon', null],
        'status' => [parent::class, 'status', null],
        'type' => [parent::class, 'type', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'vatNumber' => [parent::class, 'vatNumber', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
