<?php

namespace ContainerLjcKSR4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_85kCoCXService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private '.service_locator.85kCoCX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.85kCoCX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\EmailTestController::testEmail' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\EmailTestController::testEmail()', 'getEmailTestControllertestEmailService', true],
            'App\\Controller\\EmailTestController::sendEmail' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\EmailTestController::sendEmail()', 'getEmailTestControllersendEmailService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\EmailTestController:testEmail' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\EmailTestController::testEmail()', 'getEmailTestControllertestEmailService', true],
            'App\\Controller\\EmailTestController:sendEmail' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\EmailTestController::sendEmail()', 'getEmailTestControllersendEmailService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EmailTestController::testEmail' => '?',
            'App\\Controller\\EmailTestController::sendEmail' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EmailTestController:testEmail' => '?',
            'App\\Controller\\EmailTestController:sendEmail' => '?',
        ]);
    }
}
