<?php

namespace ContainerLjcKSR4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSystemUserCommand_LazyService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateSystemUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateSystemUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-system-user', [], 'Create a new system user', false, #[\Closure(name: 'App\\Command\\CreateSystemUserCommand')] fn (): \App\Command\CreateSystemUserCommand => ($container->privates['App\\Command\\CreateSystemUserCommand'] ?? $container->load('getCreateSystemUserCommandService')));
    }
}
