<?php

namespace ContainerLjcKSR4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWTManagerService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private 'App\Security\JWTManager' shared autowired service.
     *
     * @return \App\Security\JWTManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Security/JWTManager.php';

        $a = ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService'));

        if (isset($container->privates['App\\Security\\JWTManager'])) {
            return $container->privates['App\\Security\\JWTManager'];
        }

        return $container->privates['App\\Security\\JWTManager'] = new \App\Security\JWTManager($a);
    }
}
