<?php

namespace ContainerLjcKSR4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWTEventListenerService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private 'App\Security\JWTEventListener' shared autowired service.
     *
     * @return \App\Security\JWTEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Security/JWTEventListener.php';

        return $container->privates['App\\Security\\JWTEventListener'] = new \App\Security\JWTEventListener(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\CustomerUserRepository'] ?? $container->load('getCustomerUserRepositoryService')), ($container->privates['App\\Repository\\SystemUserRepository'] ?? $container->load('getSystemUserRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
