<?php

namespace ContainerLjcKSR4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicInvitationControllerService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the public 'App\Controller\PublicInvitationController' shared autowired service.
     *
     * @return \App\Controller\PublicInvitationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PublicInvitationController.php';

        $container->services['App\\Controller\\PublicInvitationController'] = $instance = new \App\Controller\PublicInvitationController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\PublicInvitationController', $container));

        return $instance;
    }
}
