<?php

namespace ContainerLjcKSR4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelProductionDebugContainer
{
    /**
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Command/DebugFirewallCommand.php';

        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.JqHPQCR'] ?? self::get_ServiceLocator_JqHPQCRService($container)), ($container->privates['.service_locator.EfMYNB.'] ?? $container->load('get_ServiceLocator_EfMYNB_Service')), ['customer_api' => [($container->privates['debug.security.authenticator.jwt.customer_api'] ?? $container->load('getDebug_Security_Authenticator_Jwt_CustomerApiService')), ($container->privates['debug.security.authenticator.json_login.customer_api'] ?? $container->load('getDebug_Security_Authenticator_JsonLogin_CustomerApiService'))], 'system_api' => [($container->privates['debug.security.authenticator.jwt.system_api'] ?? $container->load('getDebug_Security_Authenticator_Jwt_SystemApiService')), ($container->privates['debug.security.authenticator.json_login.system_api'] ?? $container->load('getDebug_Security_Authenticator_JsonLogin_SystemApiService'))], 'main' => [($container->privates['debug.security.authenticator.form_login.main'] ?? $container->load('getDebug_Security_Authenticator_FormLogin_MainService'))]], false);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
