<?php

namespace ContainerHpzybar;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerInvitationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CustomerInvitationController' shared autowired service.
     *
     * @return \App\Controller\CustomerInvitationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CustomerInvitationController.php';

        $container->services['App\\Controller\\CustomerInvitationController'] = $instance = new \App\Controller\CustomerInvitationController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\CustomerInvitationController', $container));

        return $instance;
    }
}
