<?php

namespace ContainerHpzybar;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateTestUserCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateTestUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateTestUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-test-user', [], 'Create test users for authentication testing', false, #[\Closure(name: 'App\\Command\\CreateTestUserCommand')] fn (): \App\Command\CreateTestUserCommand => ($container->privates['App\\Command\\CreateTestUserCommand'] ?? $container->load('getCreateTestUserCommandService')));
    }
}
