<?php

namespace ContainerHpzybar;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailTestControllersendEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..V3RrT8.App\Controller\EmailTestController::sendEmail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator..V3RrT8'] ?? $container->load('get_ServiceLocator__V3RrT8Service'));

        if (isset($container->privates['.service_locator..V3RrT8.App\\Controller\\EmailTestController::sendEmail()'])) {
            return $container->privates['.service_locator..V3RrT8.App\\Controller\\EmailTestController::sendEmail()'];
        }

        return $container->privates['.service_locator..V3RrT8.App\\Controller\\EmailTestController::sendEmail()'] = $a->withContext('App\\Controller\\EmailTestController::sendEmail()', $container);
    }
}
