<?php

namespace ContainerV61y47y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A2GrhyGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a2GrhyG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a2GrhyG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\EmailTestController::testEmail' => ['privates', '.service_locator..V3RrT8.App\\Controller\\EmailTestController::testEmail()', 'getEmailTestControllertestEmailService', true],
            'App\\Controller\\EmailTestController::sendEmail' => ['privates', '.service_locator..V3RrT8.App\\Controller\\EmailTestController::sendEmail()', 'getEmailTestControllersendEmailService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\EmailTestController:testEmail' => ['privates', '.service_locator..V3RrT8.App\\Controller\\EmailTestController::testEmail()', 'getEmailTestControllertestEmailService', true],
            'App\\Controller\\EmailTestController:sendEmail' => ['privates', '.service_locator..V3RrT8.App\\Controller\\EmailTestController::sendEmail()', 'getEmailTestControllersendEmailService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\EmailTestController::testEmail' => '?',
            'App\\Controller\\EmailTestController::sendEmail' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\EmailTestController:testEmail' => '?',
            'App\\Controller\\EmailTestController:sendEmail' => '?',
        ]);
    }
}
