<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLjcKSR4\App_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLjcKSR4/App_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerLjcKSR4.legacy');

    return;
}

if (!\class_exists(App_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerLjcKSR4\App_KernelProductionDebugContainer::class, App_KernelProductionDebugContainer::class, false);
}

return new \ContainerLjcKSR4\App_KernelProductionDebugContainer([
    'container.build_hash' => 'LjcKSR4',
    'container.build_id' => '5635f16e',
    'container.build_time' => 1756964889,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLjcKSR4');
