<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHpzybar\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHpzybar/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHpzybar.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHpzybar\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHpzybar\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hpzybar',
    'container.build_id' => 'ccaaca59',
    'container.build_time' => 1756916928,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHpzybar');
